feat(build): improve logging

diff --git a/git-prints b/git-prints
--- a/git-prints
+++ b/git-prints
@@ -171,7 +171,7 @@ _build() {
   _git_dir="${_dest}.git"
   _git_config="${_git_dir}/config"
 
-  printf "Copy ${_fmt_green}%s${_fmt_clear} to ${_fmt_green}%s${_fmt_clear}\n" "$_src" "$_git_config"
+  printf "\nCopy ${_fmt_green}%s${_fmt_clear} to ${_fmt_green}%s${_fmt_clear}\n" "$_src" "$_git_config"
 
   if [ -a "$_git_dir" ]; then
     printf "$_log_warning" "$_git_dir already exists. Ignoring..."
@@ -181,7 +181,11 @@ _build() {
   if ! [ "$GIT_PRINTS_DRY_RUN" == 1 ]; then
     mkdir -p "$_git_dir"
     cp "$_src" "$_git_config"
-    git -C "$_dest" init && git -C "$_dest" pull
+    printf "${_fmt_blue}%s${_fmt_clear}\n" "init..."
+    git -C "$_dest" init || return 1
+    printf "${_fmt_blue}%s${_fmt_clear}\n" "pull..."
+    git -C "$_dest" pull || return 1
+    return 0
   fi
 }
 
@@ -196,7 +200,9 @@ _orchestrate_build() {
   mapfile -t _prints < <(fd -t f "^config$" "$_prints_storage" --unrestricted)
 
   for _print in "${_prints[@]}"; do
-    _build "$_print"
+    if ! _build "$_print"; then
+      printf "$_log_error" "failed to init $_print"
+    fi
   done
 }
 
